version: '3.4'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - '5434:5432'







